name: leanyf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.3
  - anaconda
  - toolz
  - scikit-learn
  - cudnn
  - pip
  - tensorflow==2.3.0
  - optuna==2.6.0
  - pip:
    - cudatoolkit==10.1
    - pycm
    - wandb
