name: leanyf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.3
  - anaconda
  - toolz
  - scikit-learn
  - pip
  - tensorflow==2.3.0
  - optuna==2.6.0
  - pip:
    #- cudatoolkit==10.1
    - wandb
    - dill==0.3.4
    - baycomp==1.0.2
    - tensorflow-addons==0.13.0
    - pandas
    - IPython
    - h5py==2.10.0/3.4.0
